service: flask-serverless

provider:
  name: aws
  runtime: python3.12
  region: us-east-1

# functions:
#   api:
#     handler: app.handler
#     events:
#       - httpApi: '*'

# plugins:
#   - serverless-python-requirements

functions:
  api:
    handler: wsgi_handler.handler  # This is provided by the serverless-wsgi plugin
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: app.app  # points to app.py and the 'app' variable inside itgit 